name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!!"
      - name: Multi line shell command run
        run: |
          echo "Hope you are well"
          echo "I am good too"
      - name: Print goodbye
        run: echo "Done - bye!"
